# Numpy

* C언어로 구현된 라이브러리로, 고성능 수치계산을 위한 기능 제공
* 행렬 기반 계산에 유용한 라이브러리
* PyTorch의 문법은 numpy와 유사하고, numpy도 데이터 과학을 위해 꼭 정리해야 하는 라이브러리

### 파이썬 리스트와 numpy

* 파이썬 리스트는 행렬 기반 계산에는 활용하기 어려움
* numpy 행렬 연산은 C언어로 구현된 내부 코드로 실행되므로, 파이썬에 비해 속도가 빠름
* 머신러닝 및 딥러닝에서는 행렬 기반 데이터 가공 및 연산이 필요하므로, numpy와 같은 라이브러리가 유용하게 쓰일 수 있음

In [2]:
data1 = [1, 2, 3]
data2 = [4, 5, 6]

print(data1 + data2)  # List concatenation

[1, 2, 3, 4, 5, 6]


### numpy의 일반적인 import 형태

In [3]:
import numpy as np

### ndarray

* numpy의 핵심은 ndarray 클래스
* ndarray는 다차원 행렬 자료 구조 지원
* ndarray와 파이썬 리스트 차이점

  * 파이썬 리스트
    * 리스트내에 각 원소의 타입이 다를 수 있음
    * 내부 연결 리스트로 구현되어, 각 원소의 저장 위치가 다를 수 있음
  
  * numpy ndarray
    * 각 원소의 타입이 동일함
    * 각 원소가 이어진 메모리 공간에 배치됨
    * 메모리 및 계산 속도 최적화
    

### ndarray 생성

In [ ]:
data3 = np.array([1, 2, 3]) # 1차원 배열 생성
print(data3, type(data3))

[1 2 3] <class 'numpy.ndarray'>


In [8]:
print(data3.shape) # 형태 확인

(3,)


In [11]:
print(data3.ndim) # 차원 확인

1


In [ ]:
data4 = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 배열 생성
print(data4.shape, data4.ndim)

(2, 3) 2


### reshape() : 배열 구조 변경

In [16]:
data5 = np.array([1,2,3,4,5,6])
print(data5)
data5 = data5.reshape(3, 2) # 2차원 배열로 변환
print(data5)
data5 = data5.reshape(3, -1) # -1은 자동 계산
print(data5)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


### numpy 데이터 타입 정리

* numpy에서 지원하는 다양한 데이터 타입이 있음
  * 주로, int와 float를 사용하지만, 데이터 타입이 무엇이 있는지 참고로 정리하기로 함
  * 데이터 타입은 numpy 버전에 따라 다를 수 있지만, 기본적인 데이터 타입은 동일함
  