# Tensor의 원소 접근 방법 (indexing)

* tensor의 특정 데이터를 가져오는 기능을 indexing 이라고 함

In [1]:
import numpy as np
import torch

In [2]:
data1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(data1)  # tensor([[1., 2., 3.], [4., 5., 6.]])
print(data1[1,1]) # tensor(5.)
print(data1[:,1]) # 슬라이싱, :는 전체를 의미
print(data1[:, :])
print(data1[:1, :2]) # 0행부터 1행 전까지, 0열부터 2열 전까지

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([2., 5.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.]])


### boolean indexing

* 조건 필터링과 검색을 동시에 할 수 있어서, 유용하게 쓰이는 인덱싱 기법

In [8]:
data2 = torch.FloatTensor([[1,2,3], 
                           [5,5,5]])
data3 = data2 > 3

print(data3)
print(data2[data3]) # True인 부분만 출력
print(data2[(data2 > 3) & (data2 < 6)]) # 논리연산자 & (and), | (or) 사용 가능

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([5., 5., 5.])
tensor([5., 5., 5.])


### fancy indexing

* 다른 배열로 배열을 인덱싱할 수 있는 기능
* 이를 통해, 복잡한 배열의 연속되지 않은 일부분을 빠르게 접근할 수 있음

In [15]:
data4 = torch.randn(4, 3)
print(data4)
print("\n")

# 특정 행 배열 추출하기
print(data4[[1, 2, 0]]) # 1행, 2행, 0행 순서로 출력
print("\n")
print(data4[ [1, -1]]) # 1행과 마지막 행
print("\n")

# 특정 행과 열 추출하기(참고)
print(data4[[1,2]][:, [0,2]]) # 1행과 2행에서 0열과 2열 추출
print("\n")
print(data4[[1, -1]][: , [0]]) # 1행과 마지막 행에서 0열 추출

tensor([[ 1.2218,  0.7857, -0.9313],
        [-0.4149, -0.7377,  0.2018],
        [-1.9294,  2.0286, -0.2240],
        [-1.3336,  0.3913, -0.6269]])


tensor([[-0.4149, -0.7377,  0.2018],
        [-1.9294,  2.0286, -0.2240],
        [ 1.2218,  0.7857, -0.9313]])


tensor([[-0.4149, -0.7377,  0.2018],
        [-1.3336,  0.3913, -0.6269]])


tensor([[-0.4149,  0.2018],
        [-1.9294, -0.2240]])


tensor([[-0.4149],
        [-1.3336]])


### 배열 복사 : 텐서 객체.clone().detach()

* PyTorch에서 tensor를 복사하는 다양한 방법이 존재하지만,
* 이 중에서, 위 메서드를 사용하는 것이 가장 깔끔한 방법이라고 함
    * clone() : 기존 텐서객체의 내용을 복사한 텐서 생성
    * detach() : 기존 텐서객체 그래프에서 분리된 텐서로 구성

In [16]:
data5 = torch.FloatTensor([[1,2,3],
                            [4,5,6]])

print(data5)
print("\n")
data6 = data5[:2, :2]
print(data6)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


tensor([[1., 2.],
        [4., 5.]])


In [18]:
data6[1, 1] = 4
print(data5) # data5도 변경됨 (얕은 복사)
print("\n")
print(data6)

tensor([[1., 2., 3.],
        [4., 4., 6.]])


tensor([[1., 2.],
        [4., 4.]])


In [19]:
data7 = data5[:2, :2].clone().detach() # 깊은 복사
data7[1, 1] = 10
print(data5) # data5는 변경되지 않음
print("\n")
print(data7)

tensor([[1., 2., 3.],
        [4., 4., 6.]])


tensor([[ 1.,  2.],
        [ 4., 10.]])
