# Tensor 조건 연산과 저장

In [1]:
import numpy as np
import torch

### tensor 조건 연산 : where()

* torch.where(조건, 참일 때의 배열, 거짓일 때의 배열)

In [2]:
# 조건에 맞는 값 indexing

data1 = torch.FloatTensor([7, 2, 0, 4, 1])
index = torch.where(data1< 3) # 3보다 작은 값의 index 반환
print(index) # (tensor([1, 2, 4]),)
print(data1[index]) # tensor([2., 0., 1.])

(tensor([1, 2, 4]),)
tensor([2., 0., 1.])


In [5]:
# 조건에 맞는 값 특정 다른 값으로 변환

print(data1)
data2 = torch.where(data1 < 3, -1, 1) # 조건에 맞으면 -1, 틀리면 1로 원소 값을 수정
print(data2)

tensor([7., 2., 0., 4., 1.])
tensor([ 1, -1, -1,  1, -1])


In [7]:
# 다차원 배열에도 적용 가능

data3 = torch.FloatTensor([[1, 2, 3], [4, 5 , 6]])
data4 = torch.where(data3 < 3, -1, 1) # 조건에 맞으면 -1, 틀리면 1로 원소 값을 수정
print(data4)

tensor([[-1, -1,  1],
        [ 1,  1,  1]])


### tensor 데이터 분석

* min(), max(), sum(), mean(), var(), std() : 최대값, 최소값, 합계값, 평균값, 분산값, 표준편차값
* argmin(), argmax() : 최소값의 인덱스 번호, 최대값의 인덱스 번호

In [8]:
data5 = torch.FloatTensor([[1, 2, 3], [4, 5 , 6]])

print(data5.min())
print(data5.max())
print(data5.mean())
print(data5.sum())
print(data5.std())
print(data5.var())
print(data5.argmax()) # 최댓값의 index 반환
print(data5.argmin()) # 최솟값의 index 반환

tensor(1.)
tensor(6.)
tensor(3.5000)
tensor(21.)
tensor(1.8708)
tensor(3.5000)
tensor(5)
tensor(0)


### 텐서를 파일로 저장하고, 불러오기

In [9]:
# 한 개의 텐서 저장
# save()로 파일로 저장 가능

data1 = torch.linspace(1, 5, 4)
print(data1)
torch.save(data1, 'data1.pt')

tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [10]:
# 한 개의 텐서 읽어오기
# load()로 파일로 저장된 1차원 배열을 읽어올 수 있음

data2 = torch.load('data1.pt')
print(data2)

tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [ ]:
# 한개 이상의 텐서 저장
# 각 배열을 key=배열 로 key값을 지정할 수 있음

data6 = torch.linspace(1, 5, 4)
data7 = torch.linspace(6, 10, 5)
data8 = torch.linspace(11, 15, 6)
print(data6)
print(data7)
print(data8)
torch.save({'data6': data6, 'data7': data7, 'data8': data8}, 'data_multi.pt')
print("\n")

# 한 개 이상의 텐서 읽어오기
loaded_data = torch.load('data_multi.pt')
print(loaded_data['data6'])
print(loaded_data['data7'])
print(loaded_data['data8'])

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 6.,  7.,  8.,  9., 10.])
tensor([11.0000, 11.8000, 12.6000, 13.4000, 14.2000, 15.0000])


tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 6.,  7.,  8.,  9., 10.])
tensor([11.0000, 11.8000, 12.6000, 13.4000, 14.2000, 15.0000])


: 