# PyTorch

* numpy가 지원하는 연산들을 GPU에서 할 수 있도록 함
* 높은 유연성과 성능을 제공하는 딥러닝 지원
    * 따라서, numpy와 유사한 측면이 많음



In [1]:
import torch

## Tensor 생성

* Tensor는 numpy의 ndarray와 상당히 유사한 구조를 지님

### scala (0D 텐서)

* scala는 numpy로 만들 수 있음

In [ ]:

import numpy as np
data1 = np.array(10)
print(data1, data1.ndim, data1.shape) # ndim: 차원 수, shape: 각 차원의 크기

10 0 ()


### vector (1D 텐서)

* vector 부터는 pytorch의 tensor로 만들 수 있음
* shape는 torch.size([3])와 같이 표현됨

In [6]:
data1 = torch.FloatTensor([1,2]) # 1, 2 원소를 갖는 1차원 텐서
print(data1, data1.dim(), data1.shape)

data2 = torch.FloatTensor(3) # 크기 3의 1차원 텐서 (초기화 X)
print(data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([1.4013e-45, 0.0000e+00, 1.4013e-45]) 1 torch.Size([3])


### Matrix (2D 텐서)

In [9]:
data3 = torch.FloatTensor(3,2) # 3x2 크기의 2차원 텐서 (초기화 X)
print(data3, data3.dim(), data3.shape)

data4 = torch.FloatTensor([[1, 2], [3, 4], [5, 6]]) # 3x2 크기의 2차원 텐서
print(data4, data4.dim(), data4.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


### Tensor (3D 텐서)

In [ ]:
data5 = torch.FloatTensor(3, 2, 4) # 3x2x4 크기의 3차원 텐서 (초기화 X)
print(data5, data5.dim(), data5.shape)

data6 = torch.FloatTensor([[[1, 2, 3, 4], [5, 6, 7, 8]],
                            [[9, 10, 11, 12], [13, 14, 15, 16]],
                            [[17, 18, 19, 20], [21, 22, 23, 24]]]) # 3x2x4 크기의 3차원 텐서

print(data6, data6.dim(), data6.shape)

tensor([[[4.9601e-04, 2.1244e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]]) 3 torch.Size([3, 2, 4])
tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]],

        [[17., 18., 19., 20.],
         [21., 22., 23., 24.]]]) 3 torch.Size([3, 2, 4])


: 