# Tensor 생성 주요 메서드

* torch.zeros(x, y, z) : 0 값으로 shape 모양의 텐서 생성
* torch.ones(x, y, z) : 1값으로 shape 모양의 텐서 생성
* torch.rand(x, y, z) : 0부터 1 사이에 균일한 확률 분포로 랜덤한 값을 가진 (x, y) shape의 텐서 생성
* torch.randn(x, y, z) : 기댓값이 0이고, 표준 편차가 1인 가우시안 표준 정규 분포를 따르는 랜덤값을 가진 (x, y) shape의 텐서 생성
* torch.full(x, y, z) : a값으로, shape 모양의 텐서 생성

* torch.zeros_like(tensor) : 인자로 들어간 tensor 객체와 동일 shape를 가지되, 각 원소값은 0으로 이루어진 텐서 생성
* torch.ones_like(tensor) : 인자로 들어가 tensor 객체와 동일 shape를 가지되, 각 원소값은 1로 이루어진 텐서 생성
* torch.rand_like(tensor) : 0부터 1사이에 균일한 확률 분포로 랜덤한 값을 가진 (x, y) shape의 텐서 생성
* torch.randn_like(tensor) : 인자로 들어간 tensor 객체와 동일 shape를 가지되, 각 원소값은 randn()의 랜덤값으로 채워진 텐서 생성
* torch.full_like(tensor) : 인자로 들어간 tensor 객체와 동일 shape를 가지되, 각 원소값은 a값으로 이루어진 텐서 생성

* torch.empty(x, y, z) : 초기화 되지 않은 값을 가진 (x, y) shape의 행렬 생성


* shape은 여러 차원이 될 수 있음
* 각 메서드에 dtype = type 인자를 넣어, 데이터 타입 명시 가능

In [2]:
import numpy as np
import torch

In [4]:
data1 = torch.zeros(2, dtype=torch.float32)
data2 = torch.ones(2, 2, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)
data4 = torch.randn(2, 2, 3, 4)
data5 = torch.full((2, 3), 10)

In [6]:
# 형태 확인
print("data1 shape:", data1.shape)
print("data2 shape:", data2.shape)
print("data3 shape:", data3.shape)
print("data4 shape:", data4.shape)
print("data5 shape:", data5.shape)

data1 shape: torch.Size([2])
data2 shape: torch.Size([2, 2])
data3 shape: torch.Size([2, 2, 3])
data4 shape: torch.Size([2, 2, 3, 4])
data5 shape: torch.Size([2, 3])


In [9]:
# 배열의 차원을 나타 냄
print("data1 ndim:", data1.ndim, data1.dim())
print("data2 ndim:", data2.ndim, data2.dim())
print("data3 ndim:", data3.ndim, data3.dim())
print("data4 ndim:", data4.ndim, data4.dim())
print("data5 ndim:", data5.ndim,  data5.dim())


data1 ndim: 1 1
data2 ndim: 2 2
data3 ndim: 3 3
data4 ndim: 4 4
data5 ndim: 2 2


In [11]:
# 데이터 타입 확인
print("data1 dtype:", data1.dtype)
print("data2 dtype:", data2.dtype)
print("data3 dtype:", data3.dtype)
print("data4 dtype:", data4.dtype)
print("data5 dtype:", data5.dtype)

data1 dtype: torch.float32
data2 dtype: torch.float64
data3 dtype: torch.float16
data4 dtype: torch.float32
data5 dtype: torch.int64


In [13]:
# 데이터 사이즈(원소 갯수) 확인
# numpy와 달리 size가 아닌 size() 메서드 제공
print("data1 size:", data1.size())
print("data2 size:", data2.size())
print("data3 size:", data3.size())
print("data4 size:", data4.size())
print("data5 size:", data5.size())

data1 size: torch.Size([2])
data2 size: torch.Size([2, 2])
data3 size: torch.Size([2, 2, 3])
data4 size: torch.Size([2, 2, 3, 4])
data5 size: torch.Size([2, 3])


In [15]:
# 각 원소 값을 직접 대입하여 tensor 선언
data6 = torch.FloatTensor([[1,2], [3,4]])
data7 = torch.DoubleTensor([[5,6], [7,8]])
data8 = torch.LongTensor([[9,10], [11,12]])

# shape을 기반으로 tensor 선언
data9 = torch.FloatTensor(2,3,5)
data10 = torch.IntTensor(3,3,2,4)
data11 = torch.LongTensor(4,4)

print("data6:\n", data6)
print("data7:\n", data7)
print("data8:\n", data8)
print("data9:\n", data9)
print("data10:\n", data10)
print("data11:\n", data11)

data6:
 tensor([[1., 2.],
        [3., 4.]])
data7:
 tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)
data8:
 tensor([[ 9, 10],
        [11, 12]])
data9:
 tensor([[[-3.6561e+13,  1.6283e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
data10:
 tensor([[[[-704248768,       1162,          0,          0],
          [         0,          0,          0,          0]],

         [[         0,          0,          0,          0],
          [         0,          0,          0,          0]],

         [[         0,          0,          0,          0],
          [         0,          0,          0,          0]]],



In [16]:
# _like() 로 tensor 생성
data12 = torch.full_like(data5, 20)

print("data12:\n", data12)
print("data5:\n", data5)

data12:
 tensor([[20, 20, 20],
        [20, 20, 20]])
data5:
 tensor([[10, 10, 10],
        [10, 10, 10]])
