# Tensor 변환

In [2]:
import numpy as np
import torch

### reshape() : 배열 구조 변경

In [4]:
data1 = torch.DoubleTensor([[1,2,3],[4,5,6]])
print("data1:", data1, data1.shape)
data1 = data1.reshape(3,2)
print("reshaped data1:", data1, data1.shape)
data1 = data1.reshape(1, -1) # -1은 열을 행의 갯수에 맞춰 자동 계산
print("reshaped data1 with -1:", data1, data1.shape)

data1: tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])
reshaped data1: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64) torch.Size([3, 2])
reshaped data1 with -1: tensor([[1., 2., 3., 4., 5., 6.]], dtype=torch.float64) torch.Size([1, 6])


### view() : 텐서 구조 변경

* pytorch 에서는 numpy 처럼 reshape()로 배열 구조를 변경할 수 있지만, reshape()보다 view() 메서드를 많이 사용함
* view() 메서드는 reshape()와 사용법은 동일

* 원소 수를 유지하면서 텐서의 크기를 변경할 때 많이 사용하며, 매우 중요함

* **높이, 너비, 깊이** 순서로 기억하는 편이 좋음

In [8]:
data2 = torch.DoubleTensor([
  [[1,2,3],
   [4,5,6]],
   [[7,8,9], 
   [10,11,12]],
])

print("data2:", data2, data2.shape)
print("data2 height(k):", data2.size(0))  # 첫번째 차원의 크기
print("data2 width(n):", data2.size(1))   # 두번째 차원의 크기
print("data2 depth(m):", data2.size(2))   # 세번째 차원의 크기

data2: tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=torch.float64) torch.Size([2, 2, 3])
data2 height(k): 2
data2 width(n): 2
data2 depth(m): 3


In [11]:
data2 = data2.view(2, -1) # (2, ?)으로 구성, -1은 자동 계산, (2, 2x3)이 됨
print("reshaped data2 with -1:", data2, data2.shape)

data2 = data2.view(-1, 3) # (?, 3)으로 구성, -1은 자동 계산, (4, 3)이 됨
print("reshaped data2 with -1:", data2, data2.shape)

data2 = data2.view(3, 2, -1) # (3, 2, ?)으로 구성, -1은 자동 계산, (3, 2, 2)가 됨
print("reshaped data2 with -1:", data2, data2.shape)

reshaped data2 with -1: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64) torch.Size([2, 6])
reshaped data2 with -1: tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64) torch.Size([4, 3])
reshaped data2 with -1: tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64) torch.Size([3, 2, 2])


### squeeze() : 텐서 차원 압축

* 차원이 1인 경우, 해당 차원을 제거

In [13]:
data3 = torch.FloatTensor([ [1], [2], [3] ])
data4 = data3.squeeze()  # 차원 축소

print("data3:", data3, data3.dim(), data3.shape)
print("data4 (squeezed data3):", data4, data4.dim(), data4.shape)

data3: tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
data4 (squeezed data3): tensor([1., 2., 3.]) 1 torch.Size([3])


### unsqueeze() : 특정 위치에 1인 차원을 추가

In [18]:
data5 = torch.FloatTensor([1,2,3])
data5_5 = data5.unsqueeze(0)  # 차원 확장
data6 = data5.unsqueeze(1)  # 차원 확장

print("data5:", data5, data5.dim(), data5.shape)
print("data5_5 (unsqueezed data5 at dim 0):", data5_5, data5_5.dim(), data5_5.shape)
print("data6 (unsqueezed data5):", data6, data6.dim(), data6.shape)

data5: tensor([1., 2., 3.]) 1 torch.Size([3])
data5_5 (unsqueezed data5 at dim 0): tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])
data6 (unsqueezed data5): tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])


### 데이터 타입 변환(type)

In [4]:
data1 = torch.zeros(2, dtype=torch.float32)
data2 = torch.ones(2, 4, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)
print("data1 (zeros):", data1, data1.dtype)
print("data2 (ones):", data2, data2.dtype)
print("data3 (random):", data3, data3.dtype)


data1 = data1.type(torch.double)
data2 = data2.type(torch.int)
data3 = data3.type(torch.double)
print("data1 converted to double:", data1, data1.dtype)
print("data2 converted to int:", data2, data2.dtype)
print("data3 converted to double:", data3, data3.dtype)

data1 (zeros): tensor([0., 0.]) torch.float32
data2 (ones): tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64) torch.float64
data3 (random): tensor([[[0.2026, 0.0146, 0.7158],
         [0.8604, 0.2642, 0.7036]],

        [[0.0859, 0.0186, 0.1924],
         [0.8662, 0.6860, 0.7715]]], dtype=torch.float16) torch.float16
data1 converted to double: tensor([0., 0.], dtype=torch.float64) torch.float64
data2 converted to int: tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32) torch.int32
data3 converted to double: tensor([[[0.2026, 0.0146, 0.7158],
         [0.8604, 0.2642, 0.7036]],

        [[0.0859, 0.0186, 0.1924],
         [0.8662, 0.6860, 0.7715]]], dtype=torch.float64) torch.float64


### T: 전치(transpose) 행렬

* 행과 열을 교환하여 얻는 행렬을 의미, $A^T$로 표현

In [5]:
print(data2)
data2 = data2.T  # 전치 행렬
print("data2 transposed:", data2)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
data2 transposed: tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)


### numpy와 pytorch

* PyTorch는 numpy의 ndarray를 GPU에서 실행시킬 수 있도록 하기 위해 개발되었으므로,
* PyTorch의 tensor와 numpy의 ndarray는 서로 변환 가능
* 이를 위해 PyTorch에서 다음 메서드 제공
  * 텐서객체.numpy() : tensor 객체를 numpy의 ndarray 객체로 변환 
  * torch.from_numpy() : numpy의 ndarray 를 tensor 객체로 변환

In [9]:
data7 = np.array([[1,2], [3,4]])
print("data7 (numpy array):", data7, type(data7))
print("\n")
data8 = torch.from_numpy(data7)  # numpy array -> torch tensor
print("data8 (from numpy):", data8, type(data8))
print("\n")
data9 = data8.numpy()  # torch tensor -> numpy array
print("data9 (to numpy):", data9, type(data9))

data7 (numpy array): [[1 2]
 [3 4]] <class 'numpy.ndarray'>


data8 (from numpy): tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


data9 (to numpy): [[1 2]
 [3 4]] <class 'numpy.ndarray'>


### arange() : 1차원 tensor 생성

In [11]:
data10 = torch.arange(1, 5)
data11 = torch.arange(1, 5, 2)
print(data10)  # tensor([1, 2, 3, 4])
print(data11)  # tensor([1, 3])

tensor([1, 2, 3, 4])
tensor([1, 3])


### linspace() : 범위 내 1차원 tensor 균등 생성

* torch.linspace(start, stop, count)

In [12]:
data12 = torch.linspace(1, 5, 4)
print(data12)  # tensor([1.0000, 2.3333, 3.6667, 5.0000])

tensor([1.0000, 2.3333, 3.6667, 5.0000])
