# Tensor 연산

* 본래 행렬 곱셉은 앞 행렬의 행의 갯수와 뒷 행렬의 열의 갯수가 같아야 행렬간 곱셉이 가능하지만,
* tensor 연산은 shape가 동일해야 하고, 행과 열이 같은 값끼리 연산이 됨

In [2]:
import numpy as np
import torch

In [9]:
data1 = torch.randn(3, 2)
data2 = torch.randn(2, 3)
data1 * data2 # shape 이 다르기 때문에 브로드캐스팅 불가

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [11]:
data3 = torch.full((3, 3), 2)
data4 = torch.full((3, 3), 1)
print(data3 + data4) # shape 이 같기 때문에 브로드캐스팅 가능
print(data3 - data4)
print(data3 * data4)
print(data3 / data4)


tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [12]:
data5 = torch.full((3, 2), 2)
data6 = torch.full((2, 3), 1)
torch.matmul(data5, data6) # 행렬 곱셈은 브로드캐스팅과 무관하게 가능

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])