# Tensor 고급 연산 정리

### PyTorch와 텐서간의 곱셈

* torch.matmul() 메서드가 다양한 텐서 곱셈을 지원하므로, 상세히 이해할 필요가 있음
* 이외에 torch.mm()은 2D 텐서, torch.bmm()은 3D 텐서 간의 연산만 지원하며, matmul()과의 차이점도 알아둘 필요가 있음

  * matmul()은 텐서의 shape 등에 따라, 다양한 계산이 가능하고, broadcasting도 지원하므로, 자칫 예상치 못한 연산이 될 수도 있음
  * 디버깅을 위해, 기대한 케이스에 대해서만 명확한 계산을 하는 것이 필요하다면, torch.mm(), torch.bmm() 사용을 고려할 필요도 있음

### 1D 텐서(벡터) X 1D 텐서(벡터)의 곱셈

* 1D 텐서(벡터) 끼리의 곱셈은 벡터의 내적값, 즉 스칼라(scala) 값을 리턴함
* 두 벡터는 동일 차원이어야 함
* 벡터의 내적은 선형대수에서 나오는 수식으로, dot product 라고도 불리움

In [1]:
import torch

In [5]:
A = torch.full((3, ),2) # vector 생성
B = torch.full((3, ),3) # vector 생성

print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)

result = torch.matmul(A, B) # 내적 연산
print(result)

tensor([2, 2, 2]) 1 torch.Size([3])
tensor([3, 3, 3]) 1 torch.Size([3])
tensor(18)


### 2D 텐서(행렬) X 2D 텐서(행렵) 곱

* Matrix Multiplication, Inner Product, 또는 Dot Product 라고 부름
* 앞 행렬의 열의 갯수와 뒷 행렬의 행의 갯수가 같아야 행렬간 곱셈이 가능

In [6]:
A = torch.full((3, 2),2) # matrix 생성
B = torch.full((2, 3),3) # matrix 생성
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(A, B) # 행렬 곱 연산
print(result)

tensor([[2, 2],
        [2, 2],
        [2, 2]]) 2 torch.Size([3, 2])
tensor([[3, 3, 3],
        [3, 3, 3]]) 2 torch.Size([2, 3])
tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])


### 1D 텐서(벡터) X 2D 텐서(행렬)의 곱

* 벡터(vector) x 행렬(matrix) 와 행렬(matrix) x 벡터(vector)는 계산식이 다름
* 벡터는 기본적으로 열 벡터로 다룸

In [7]:
x = torch.full((3, ), 2) # vector 생성
A = torch.full((3, 2), 3) # matrix 생성

result = torch.matmul(x, A) # vector와 matrix의 행렬 곱 연산
print(result)

tensor([18, 18])


### 1D 텐서(벡터) X 3D 이상 텐서의 곱

* 1D 텐서(벡터)를 (a)라 하고,
* 3D 이상 텐서를 (b,c,d)라 하면
  * 3D 이상 텐서는 batched matrix로 간주하여, b x (c, d)가 됨
* 즉, b x((a) x (c,d))가 되므로, 1D 텐서 X 2D 텐서와 마찬가지로, a와 c로 동일해야 함
* 즉, (a) x (b, a, d)가 되고, 결과 shape는 동일한 a는 삭제되고, (b,d)가 됨 

In [8]:
x = torch.full((3,), 2 ) # vector 생성
A = torch.full((4, 3, 2), 3) # 3차원 tensor 생성
result = torch.matmul(x, A) # vector와 3차원 tensor의 행렬 곱 연산
print(result)

tensor([[18, 18],
        [18, 18],
        [18, 18],
        [18, 18]])


### 2D 텐서(행렬) X 1D 텐서(벡터)

* 행렬(matrix) x 벡터(vector) 는 행렬의 열의 수 (a, b)일 때, b와, 벡터의 차원 수(c)라고 할대, c가 같아야 하므로, 
* (a,b) x (b)가 되며, 결과 shape는 b가 삭제된 (a)가 됨

In [9]:
x = torch.full((2, ), 2)
A = torch.full((3,2), 3)

result = torch.matmul(A, x) # matrix와 vector의 행렬 곱 연산
print(result)

tensor([12, 12, 12])


### 3D 이상 텐서(행렬) X 1D 텐서(벡터)의 곱

* 3D이상 텐서를 (a, b, c)라고 하고,
  * 3D 이상 텐서는 batched matrix로 간주하여, a x (b, c)가 됨
* 1D 텐서(벡터)를 (d)라 하면,
* 즉, a x((b, c) x (d))가 되므로, 2D 텐서 X 1D 텐서 와 마찬가지로, c와 d는 동일해야 함
* 즉, (a,b,c) x (c) 가 되고, 결과 shape는 동일한 c는 삭제되고, (a,b)가  됨

In [ ]:
x = torch.full((2, ), 2)
A = torch.full((4, 3, 2), 3) # 3차원 tensor 생성
result = torch.matmul(A, x) # 3차원 tensor와 vector의 행렬 곱 연산
print(result)

tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])


### n - D텐서 (n > 2)간의 곱셈

* 기본적으로 첫번째 인자와 두번째 인자의 마지막 두 axis 차원 이외의 동일함을 가정하고, Batched Matrix Multiplication 방식으로 계산됨
  
  * Batched Matrix Multiplication 방식이해 

    * (b, m, n)은 (m, n) 행렬이 b개 있는 것이라고 볼 수 있음
    * (b, m, n) x (b, n, k)는 b 개의 (m, n)을 b개의 (n, k)와 곱하는 것이라고 볼수 있음
    * 따라서, tensor 간의 곱에서는 b자리는 동일해야 하며, (m, n), (n, k)는 행렬 곱셈과 동일한 제약사항을 가짐

  * 첫번째 인자와 두번째 인자의 마지막 두 axis 차원 이외의 차원이 동일하지 않다면, broadcasting 룰이 적용됨

    * 첫번째 인자의 마지막 두 axis 차원, 즉 matrix(m, n)과, 두번째 인자의 마지막 두 axis 차원, 즉 matrix (n, k) 사이에서만 곱하여 (m, k)으로 계산

In [14]:
data1 = torch.full((10, 1, 3, 4), 2) # 4차원 tensor 생성
data2 = torch.full((2,4,5), 3) # 3차원 tensor 생성

print(data1, data1.dim(), data1.shape)
print(data2, data2.dim(), data2.shape)
data3 = torch.matmul(data1, data2) # 4차원 tensor와 3차원 tensor의 행렬 곱 연산
print(data3, data3.dim(), data3.shape)

tensor([[[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]]]) 4 torch.Size([10, 1, 3, 4])
tensor([[[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]]) 3

In [16]:
data4 = torch.full((10, 8, 3, 4), 2) # 4차원 tensor 생성
data5 = torch.full((1, 8, 4, 5), 3) # 4차원 tensor 생성

print(data4, data4.dim(), data4.shape)
print(data5, data5.dim(), data5.shape)

data6 = torch.matmul(data4, data5) # 4차원 tensor와 4차원 tensor의 행렬 곱 연산
print(data6, data6.dim(), data6.shape)

tensor([[[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]],

         [[2, 2, 2, 2],
          [2

### torch.mm()

* 행렬곱만 지원
* 두 인자 모두 행렬 shape 이어야 함

In [19]:
data7 = torch.full((3, 4), 2)
data8 = torch.full((4, 5), 3)

print(data7, data7.dim(), data7.shape)
print(data8, data8.dim(), data8.shape)
data9 = torch.matmul(data7, data8) # 2차원 tensor와 2차원 tensor의 행렬 곱 연산
print(data9, data9.dim(), data9.shape)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]) 2 torch.Size([3, 4])
tensor([[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]) 2 torch.Size([4, 5])
tensor([[24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24],
        [24, 24, 24, 24, 24]]) 2 torch.Size([3, 5])


### torch.bmm()

* 두 인자 모두 3D 텐서 shape 이어야 함
* broadcast를 지원하지 않으므로, 마지막 두 axis 외에는 두 인자 모두 동일한 차원이어야 함

In [21]:
data10 = torch.full((3,3,4), 2) # 3차원 tensor 생성
data11 = torch.full((3,4,5), 3) # 3차원 tensor 생성

print(data10, data10.dim(), data10.shape)
print(data11, data11.dim(), data11.shape)

data12 = torch.matmul(data10, data11) # 3차원 tensor와 3차원 tensor의 행렬 곱 연산
print(data12, data12.dim(), data12.shape)

tensor([[[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]]]) 3 torch.Size([3, 3, 4])
tensor([[[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]]) 3 torch.Size([3, 4, 5])
tensor([[[24, 24, 24, 24, 24],
         [24, 24, 24, 24, 24],
         [24, 24, 24, 24, 24]],

        [[24, 24, 24, 24, 24],
         [24, 24, 24, 24, 24],
         [24, 24, 24, 24, 24]],

        [[24, 24, 24, 24, 24],
         [24, 24, 24, 24, 24],
         [24, 24, 24, 24, 24]]]) 3 torch.Size([3, 3, 5])
