## Section 1. N차원 배열 생성

### 1-1. N차원 배열(ndarray) 생성하기

In [13]:
import numpy as np
# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

# 2차원 배열
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [14]:
# np.array() 함수의 반환 타입은 numpy.ndarray 임을 확인
print(type([1, 2 , 3]))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# 튜플로부터 배열 생성
tpl = (1, 2, 3)
arr = np.array(tpl)
print(arr)

# 리스트로부터 배열 생성
lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

# 2차원 리스트로부터 배열 생성
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 배열의 형태, 차원, 크기 확인
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# shape
print(arr1.shape)  # (6,)
print(arr2.shape)  # (2, 3)

# ndim
print(arr1.ndim)  # 1
print(arr2.ndim)  # 2

# size
print(arr1.size)  # 6
print(arr2.size)  # 6

(6,)
(2, 3)
1
2
6
6
