### 3-1. 배열의 연산1 : 사칙연산/제곱/제곱근/몫/나머지

In [1]:
import numpy as np

In [3]:
# 2차원 배열
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

# 2차원 배열 (2)
arr2 = np.array([[2, 2, 2],
                 [2, 2, 2],
                 [2, 2, 2]])

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [6]:
# 덧셈
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# 뺄셈
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [10]:
# 곱셈
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
# 나눗셈
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [14]:
# 제곱
print(arr1 ** 2)
print(np.power(arr1, 2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [16]:
# 제곱근
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [18]:
# 몫
print(arr1 // arr2)
print(np.floor_divide(arr1, arr2))

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [19]:
# 나머지
print(arr1 % arr2)
print(np.mod(arr1, arr2))

[[1 0 1]
 [0 1 0]
 [1 0 1]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]
