### 3-2. 배열의 연산2: 내적(dot product)/절댓값/올림/내림/반올림/버림

In [1]:
import numpy as np

In [4]:
# 1차원 행렬
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 2, 3])

# 내적 계산
print(np.dot(arr1, arr2))  # 20

20


In [6]:
# 2차원 행렬
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

'''
[[a, b],      [[e, f],      [[a*e + b*g, a*f + b*h],
 [c, d],       [g, h]]  =   [c*e + d*g, c*f + d*h]]
'''

# 행렬 곱셈 계산
print(np.dot(mat1, mat2))

[[19 22]
 [43 50]]


In [8]:
# 절댓값
arr1 = np.array([[1, -2],
                [-4, 5]])

print(np.abs(arr1))  # [[1 2] [4 5]]


[[1 2]
 [4 5]]


In [9]:
# 올림
arr2 = np.array([[1.2, -2.5],
                [-4.7, 5.1]])

print(np.ceil(arr2))  # [[ 2. -2.] [-4.  6.]]

[[ 2. -2.]
 [-4.  6.]]


In [10]:
# 내림
arr3 = np.array([[1.2, -2.5],
                [-4.7, 5.1]])
print(np.floor(arr3))  # [[ 1. -3.] [-5.  5.]]

[[ 1. -3.]
 [-5.  5.]]


In [11]:
# 반올림

arr4 = np.array([[1.2, -2.5],
                [-4.7, 5.5]])

print(np.round(arr4))  # [[ 1. -2.] [-5.  6.]]

[[ 1. -2.]
 [-5.  6.]]


In [12]:
# 버림

arr5 = np.array([[1.2, -2.5],
                [-4.7, 5.5]])
print(np.trunc(arr5))  # [[ 1. -2.] [-4.  5.]]

[[ 1. -2.]
 [-4.  5.]]
