### 3-3. 배열의 연산3 : min/max/sum/mean/std/cumsum/median

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

In [9]:
# min()

print(np.min(arr))
print(arr.min())
print(arr.min(axis=0)) # Column-wise minimum

1
1
[1 2 3]


In [8]:
# max()

print(np.max(arr))
print(arr.max())
print(arr.max(axis=0)) # Row-wise maximum

6
6
[4 5 6]


In [13]:
# sum()

print(np.sum(arr))
print(arr.sum())
print(arr.sum(axis=0)) # Row-wise sum

21
21
[5 7 9]


In [14]:
# mean()
# 평균값

print(np.mean(arr))
print(arr.mean())
print(arr.mean(axis=0)) # Column-wise mean

3.5
3.5
[2.5 3.5 4.5]


In [15]:
# std()
# 표준편차

print(np.std(arr))
print(arr.std())
print(arr.std(axis=0)) # Column-wise standard deviation


1.707825127659933
1.707825127659933
[1.5 1.5 1.5]


In [18]:
# cumsum()
# 누적합

print(np.cumsum(arr))
print(arr.cumsum())
print(arr.cumsum(axis=0)) # Column-wise cumulative sum


[ 1  3  6 10 15 21]
[ 1  3  6 10 15 21]
[[1 2 3]
 [5 7 9]]


In [19]:
# median()
# 중앙값

print(np.median(arr))
print(arr)
print(np.median(arr, axis=0)) # Column-wise median

3.5
[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]
