### 3-4. 배열의 연산4 : 비교 연산/삼각 함수

In [1]:
import numpy as np

In [6]:
# 비교 연산
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
arr2 = np.array([[1, 0, 3], 
                 [4, -2, 9]])

# 두 배열의 요소별 비교
print(arr1 == arr2, end='\n\n')

# 두 배열의 대소 비교
print(arr1 > arr2, end='\n\n')

# equal 함수 사용
print(np.array_equal(arr1, arr2))

[[ True False  True]
 [ True False False]]

[[False  True False]
 [False  True False]]

False


In [9]:
# 삼각 함수
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# 사인 함수
print(np.sin(arr), end='\n\n')

# 코사인 함수
print(np.cos(arr), end='\n\n')

# 탄젠트 함수
print(np.tan(arr), end='\n\n')

# pi 상수
print(np.pi)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]

3.141592653589793
