### 3-5. 브로드 캐스팅(Broadcasting)

* 브로드캐스팅(broadcasting)은 NumPy에서 서로 다른 크기(shape)를 가진 배열끼리도 자동으로 연산이 가능하도록 해주는 규칙.
* 즉, 작은 배열을 큰 배열의 크기에 맞게 ‘늘려서’ 연산하는 기능

#### 브로드캐스팅은 다음 상황에서 작동

1. 두 배열의 뒤(오른쪽) 차원부터 비교한다.

2. 차원이 같거나, 둘 중 하나가 1이면 연산 가능.

3. 조건을 만족하면 NumPy가 자동으로 작은 배열을 큰 배열 모양으로 ‘복제해서 확장’한 것처럼 처리한다.
   * (실제로 복사하지는 않음 → 메모리 효율적)

In [10]:
import numpy as np

In [8]:
arr1 = np.array([[0, 0, 0],
                [1, 1, 1],
                [2, 2, 2]]) # 3x3 array
 
arr2 = np.array([[5, 6, 7]]) # 1x3 array

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [9]:
arr1 = np.array([[1, 1, 1]])

arr2 = np.array([[0],
                 [1],
                 [2]]) # 3x1 array

print(arr1 + arr2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
