### 4-1. 1차원 배열의 정렬

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10, size=10)
print(arr)

[9 8 1 2 3 2 0 7 7 9]


In [ ]:
# Sort the array in ascending order
print(np.sort(arr))

[0 1 2 2 3 7 7 8 9 9]


In [4]:
# Sort in descending order
print(np.sort(arr)[::-1])  

[9 9 8 7 7 3 2 2 1 0]
