#### 4-2. 2차원 배열의 정렬

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(15, size=(4, 4))
print(arr)

[[ 4  3  7  6]
 [12  4 12  0]
 [11 11  2 12]
 [11  9  7  4]]


In [4]:
print(np.sort(arr, axis=0))  # Sort each column

[[ 4  3  2  0]
 [11  4  7  4]
 [11  9  7  6]
 [12 11 12 12]]


In [5]:
print(np.sort(arr, axis=1))  # Sort each row

[[ 3  4  6  7]
 [ 0  4 12 12]
 [ 2 11 11 12]
 [ 4  7  9 11]]


In [6]:
print(np.sort(arr, axis=None))  # Sort the flattened array

[ 0  2  3  4  4  4  6  7  7  9 11 11 11 12 12 12]


In [7]:
# argsort()
# argsort는 정렬된 배열의 인덱스를 반환합니다.
print(np.sort(arr, axis=1), end="\n\n")
print(np.argsort(arr, axis=1))

[[ 3  4  6  7]
 [ 0  4 12 12]
 [ 2 11 11 12]
 [ 4  7  9 11]]

[[1 0 3 2]
 [3 1 0 2]
 [2 0 1 3]
 [3 2 1 0]]


In [8]:
print (np.sort(arr, axis=0), end="\n\n")
print (np.argsort(arr, axis=0))

[[ 4  3  2  0]
 [11  4  7  4]
 [11  9  7  6]
 [12 11 12 12]]

[[0 0 2 1]
 [2 1 0 3]
 [3 3 3 0]
 [1 2 1 2]]
