#### 5-1. 배열의 형태 변경 1 reshape()

#### ✔ 핵심 특징 6가지

1) 데이터는 그대로, 모양만 바뀐다
2) 총 원소 수는 반드시 같아야 한다
3) -1을 사용해 자동 계산 가능
4) 기본적으로 view(참조) 반환 → 복사가 아님
5) 순서를 바꾸는 기능이 아님
6) 딥러닝에서 자주 쓰는 대표적 reshape 패턴

#### Curse of Dimensionality(차원의 저주)

* 차원이 커질수록 데이터 분석이 기하급수적으로 어려워지는 현상.

##### ✔ 대표적인 3가지 차원의 저주

1) 공간이 너무 커져서 데이터가 희박해짐 (Sparsity)
2) 거리 기반 판단이 무의미
3) 차원이 늘수록 데이터 필요량이 지수적으로 증가

In [1]:
import numpy as np

In [9]:
arr = np.arange(12)
print(arr, arr.ndim , end='\n\n')

# Reshape to 3 rows and 4 columns
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr, reshaped_arr.ndim , end='\n\n')

# Reshape to 2 layers, 3 rows, and 2 columns
arr = arr.reshape(2, 3, 2)
print(arr, arr.ndim , end='\n\n')

# Reshape to 2 layers, 2 rows, 1 column, and 3 depth
arr = arr.reshape(2, 2, 1, 3)
print(arr, arr.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11] 1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3

[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4
