#### 5-1. 배열의 형태 변경 1 reshape()

In [1]:
import numpy as np

In [ ]:
arr = np.arange(12)
print(arr, arr.ndim , end='\n\n')

# Reshape to 3 rows and 4 columns
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr, reshaped_arr.ndim , end='\n\n')

# Reshape to 2 layers, 3 rows, and 2 columns
arr = arr.reshape(2, 3, 2)
print(arr, arr.ndim , end='\n\n')

# Reshape to 2 layers, 2 rows, 1 column, and 3 depth
arr = arr.reshape(2, 2, 1, 3)
print(arr, arr.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11] 1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4
