#### 5-1. 배열의 형태 변경2: resize(), revel()

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# resize()

arr.resize((3, 4))
print("\nResized array (3x4):\n", arr)


Resized array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
# ravel()

raveled_arr = arr.ravel()
print("\nRaveled array:\n", raveled_arr)


Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:

# reshape() -1

arr = np.arange(1, 13)
print("\nOriginal array:\n", arr)

# 자동으로 열의 크기를 계산하여 3행으로 재구성
reshaped_arr = arr.reshape(3, -1)
print("\nReshaped array (3 rows, inferred columns):\n", reshaped_arr)

# 3차원 배열로 재구성
reshaped_arr_3d = arr.reshape(3, 2, -1)
print("\nReshaped array (3x2x2):\n", reshaped_arr_3d)


Original array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array (3 rows, inferred columns):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped array (3x2x2):
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
