### 1-2. N차원 배열의 데이터 타입

In [6]:
import numpy as np

# 1차원 배열 생성
arr = np.array([10.1, 20.2, 0, 40, 50], dtype=np.float64)
print(arr, arr.dtype)

arr = arr.astype(np.int32)
print(arr, arr.dtype)

arr = arr.astype(np.bool_)
print(arr, arr.dtype)

[10.1 20.2  0.  40.  50. ] float64
[10 20  0 40 50] int32
[ True  True False  True  True] bool


In [ ]:
arr = np.array([0, 1, 2, 3])
print(arr, arr.dtype)

# 다시 실수형으로 변환
arr = arr.astype(np.float64)
print(arr, arr.dtype)

[0 1 2 3] int64
[0. 1. 2. 3.] float64


In [ ]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.5, True, 'Hello'])
print(arr, arr.dtype)

['1' '2' '3.5' 'True' 'Hello'] <U32
