#### 5-3. 배열의 형태3 : expand_dims(), squeeze()

#### expand_dims() — 차원을 “추가”하는 함수

* 특정 위치(axis)에 새로운 차원(길이 1)을 추가하는 함수.

#### squeeze() — 길이 1 차원을 “제거”하는 함수

* shape에서 길이가 1인 차원만 제거하는 함수.

In [2]:
import numpy as np

In [5]:
# expand_dims()

arr = np.array([1, 2])
print("Original array:")
print(arr, arr.shape)

arr = np.expand_dims(arr, axis=0)
print("\nArray after expanding dimensions at axis 0:")
print(arr, arr.shape)

arr = np.expand_dims(arr, axis=1)
print("\nArray after expanding dimensions at axis 1:")
print(arr, arr.shape)


Original array:
[1 2] (2,)

Array after expanding dimensions at axis 0:
[[1 2]] (1, 2)

Array after expanding dimensions at axis 1:
[[[1 2]]] (1, 1, 2)


In [21]:
# squeeze()

arr = np.array([[1, 2]])
print("\nOriginal array:")
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis=0)
print("\nArray after squeezing:")
print(arr, arr.shape, arr.ndim)

arr = np.array([[[1], 
                 [2], 
                 [3]]])

print("\nOriginal array:")
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis=0)
print("\nArray after squeezing:")
print(arr, arr.shape, arr.ndim)

arr = np.array([[[1, 2, 3]]])
print("\nOriginal array:")
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis=1)
print("\nArray after squeezing:")
print(arr, arr.shape, arr.ndim)


Original array:
[[1 2]] (1, 2) 2

Array after squeezing:
[1 2] (2,) 1

Original array:
[[[1]
  [2]
  [3]]] (1, 3, 1) 3

Array after squeezing:
[[1]
 [2]
 [3]] (3, 1) 2

Original array:
[[[1 2 3]]] (1, 1, 3) 3

Array after squeezing:
[[1 2 3]] (1, 3) 2
