#### 6-1. 배열에 원소 추가 및 삭제

In [1]:
import numpy as np

In [8]:
# python list
arr = [1, 2, 3, 4, 5]
arr.insert(2, 99)  # Insert 99 at index 2
print("Python list after insertion:", arr)

# numpy array 1차원 배열
np_arr = np.array([1, 2, 3, 4, 5])
np_arr = np.insert(np_arr, 2, 99)  # Insert 99 at index 2
print("Numpy array after insertion:", np_arr)

# numpy array 2차원 배열
np_arr_2d = np.arange(1, 13).reshape(3, 4)
np_arr_2d = np.insert(np_arr_2d, 2, 50, axis=0)  # Insert row with value 50 at index 2
print("Numpy 2D array after row insertion:\n", np_arr_2d)

np_arr_2d = np.insert(np_arr_2d, 1, 75, axis=1)  # Insert column with value 75 at index 1
print("Numpy 2D array after column insertion:\n", np_arr_2d)

# axis=None
np_arr_flat = np.array([[1, 2], [3, 4]])
np_arr_flat = np.insert(np_arr_flat, 2, 99, axis=None)  # Insert 99 at flattened index 2
print("Numpy array after insertion with axis=None:", np_arr_flat)



Python list after insertion: [1, 2, 99, 3, 4, 5]
Numpy array after insertion: [ 1  2 99  3  4  5]
Numpy 2D array after row insertion:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]
Numpy 2D array after column insertion:
 [[ 1 75  2  3  4]
 [ 5 75  6  7  8]
 [50 75 50 50 50]
 [ 9 75 10 11 12]]
Numpy array after insertion with axis=None: [ 1  2 99  3  4]


In [17]:
# delete 
arr = np.arange(1, 13).reshape(3, 4)
print("Original array:\n", arr)

# Delete row at index 1
arr_deleted_row = np.delete(arr, 1, axis=0)
print("Array after deleting row at index 1:\n", arr_deleted_row)

# Delete column at index 2
arr_deleted_col = np.delete(arr, 2, axis=1)
print("Array after deleting column at index 2:\n", arr_deleted_col)

# Delete element at flattened index 5
arr_deleted_flat = np.delete(arr, 5, axis=None)
print("Array after deleting element at flattened index 5:\n", arr_deleted_flat)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array after deleting row at index 1:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Array after deleting column at index 2:
 [[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]
Array after deleting element at flattened index 5:
 [ 1  2  3  4  5  7  8  9 10 11 12]
