#### 6-2 배열 간의 병합 

In [1]:
import numpy as np

In [4]:
# append()

arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)


Array 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array 2:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [6]:
# axis=0 (vertical append)
appended_axis0 = np.append(arr1, arr2, axis=0)
print("\nAppended along axis 0:")
print(appended_axis0)


Appended along axis 0:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [8]:
# axis=1 (horizontal append)
appended_axis1 = np.append(arr1, arr2, axis=1)
print("\nAppended along axis 1:")
print(appended_axis1)


Appended along axis 1:
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [10]:
# No axis (flattened append)
appended_no_axis = np.append(arr1, arr2)
print("\nAppended with no axis (flattened):")
print(appended_no_axis)


Appended with no axis (flattened):
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [13]:
# vstack(), hstack()
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.vstack((arr1, arr2))
print("\nVertical Stack (vstack):")
print(arr3)

arr4 = np.hstack((arr1, arr2))
print("\nHorizontal Stack (hstack):")
print(arr4)


Vertical Stack (vstack):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontal Stack (hstack):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [15]:
# concatenate()
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(10, 19).reshape(3, 3)

concatenated_axis0 = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenated along axis 0:")
print(concatenated_axis0)

concatenated_axis1 = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated along axis 1:")
print(concatenated_axis1)


Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

Concatenated along axis 1:
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
