#### 6-3. 배열 분합

In [2]:
import numpy as np

In [10]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
print("Original Array:")
print(arr)

# vsplit: 수직으로 배열을 나눔
vsplit_arr = np.vsplit(arr, 3)
print("\nVsplit Result:")
for sub_arr in vsplit_arr:
    print(sub_arr)

# hsplit: 수평으로 배열을 나눔
hsplit_arr = np.hsplit(arr, 2)
print("\nHsplit Result:")
for sub_arr in hsplit_arr:
    print(sub_arr)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Vsplit Result:
[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]

Hsplit Result:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [18]:
# 3차원 배열
arr_3d = np.random.randint(0, 10, (4, 6, 8))
print(arr_3d)



[[[5 5 2 2 2 2 2 6]
  [8 1 3 2 5 3 9 1]
  [8 3 8 6 1 5 2 6]
  [4 0 0 4 0 3 8 1]
  [4 6 3 3 6 9 6 7]
  [1 1 7 5 2 6 8 8]]

 [[2 2 7 3 6 3 5 0]
  [4 3 4 2 6 3 7 6]
  [9 7 7 4 5 3 2 5]
  [2 3 1 5 0 7 5 0]
  [6 5 4 1 9 8 3 6]
  [3 4 9 9 5 2 8 7]]

 [[1 5 8 2 9 8 7 6]
  [0 9 9 6 7 1 0 3]
  [2 9 1 9 8 7 9 8]
  [0 0 1 6 8 2 1 1]
  [7 5 8 9 2 7 3 0]
  [0 7 1 2 9 7 1 5]]

 [[2 9 0 8 2 7 4 4]
  [4 4 5 6 8 0 8 3]
  [6 4 2 8 9 8 0 9]
  [1 8 6 4 1 8 2 4]
  [8 0 3 9 0 5 3 6]
  [4 7 8 9 5 0 2 6]]]


In [20]:
arr_vsplit_3d = np.vsplit(arr_3d, 2)
print("\n3D Array Vsplit Result:")
for sub_arr in arr_vsplit_3d:
    print(sub_arr)


3D Array Vsplit Result:
[[[5 5 2 2 2 2 2 6]
  [8 1 3 2 5 3 9 1]
  [8 3 8 6 1 5 2 6]
  [4 0 0 4 0 3 8 1]
  [4 6 3 3 6 9 6 7]
  [1 1 7 5 2 6 8 8]]

 [[2 2 7 3 6 3 5 0]
  [4 3 4 2 6 3 7 6]
  [9 7 7 4 5 3 2 5]
  [2 3 1 5 0 7 5 0]
  [6 5 4 1 9 8 3 6]
  [3 4 9 9 5 2 8 7]]]
[[[1 5 8 2 9 8 7 6]
  [0 9 9 6 7 1 0 3]
  [2 9 1 9 8 7 9 8]
  [0 0 1 6 8 2 1 1]
  [7 5 8 9 2 7 3 0]
  [0 7 1 2 9 7 1 5]]

 [[2 9 0 8 2 7 4 4]
  [4 4 5 6 8 0 8 3]
  [6 4 2 8 9 8 0 9]
  [1 8 6 4 1 8 2 4]
  [8 0 3 9 0 5 3 6]
  [4 7 8 9 5 0 2 6]]]


In [21]:
hsplit_arr_3d = np.hsplit(arr_3d, 3)
print("\n3D Array Hsplit Result:")
for sub_arr in hsplit_arr_3d:
    print(sub_arr)


3D Array Hsplit Result:
[[[5 5 2 2 2 2 2 6]
  [8 1 3 2 5 3 9 1]]

 [[2 2 7 3 6 3 5 0]
  [4 3 4 2 6 3 7 6]]

 [[1 5 8 2 9 8 7 6]
  [0 9 9 6 7 1 0 3]]

 [[2 9 0 8 2 7 4 4]
  [4 4 5 6 8 0 8 3]]]
[[[8 3 8 6 1 5 2 6]
  [4 0 0 4 0 3 8 1]]

 [[9 7 7 4 5 3 2 5]
  [2 3 1 5 0 7 5 0]]

 [[2 9 1 9 8 7 9 8]
  [0 0 1 6 8 2 1 1]]

 [[6 4 2 8 9 8 0 9]
  [1 8 6 4 1 8 2 4]]]
[[[4 6 3 3 6 9 6 7]
  [1 1 7 5 2 6 8 8]]

 [[6 5 4 1 9 8 3 6]
  [3 4 9 9 5 2 8 7]]

 [[7 5 8 9 2 7 3 0]
  [0 7 1 2 9 7 1 5]]

 [[8 0 3 9 0 5 3 6]
  [4 7 8 9 5 0 2 6]]]
