### 1-3. 정해진 형식의 N차원 배열 생성하기

In [ ]:
import numpy as np

# np.zeros()
# 2x2 array of zeros
arr = np.zeros([2, 2])
print(arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
# np.ones()
# 3x5 array of ones
arr = np.ones([3, 5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# np.full()
# 2행 3열의 모든 원소가 7인 배열 생성
arr = np.full((2, 3), 7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [ ]:
# np.eye()
# 3x4 단위 행렬 생성 (k=0: 주대각선, k=1: 주대각선 위)
arr = np.eye(3, 4 , k = 0)
print(arr)
arr = np.eye(3, 4 , k = 1)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# np.zeros_like()
# arr와 동일한 shape의 0으로 채워진 배열 생성
arr_z = np.zeros_like(arr)
print(arr_z)

[[0 0 0]
 [0 0 0]]


In [12]:
# np.ones_like()
# arr와 동일한 shape의 1로 채워진 배열 생성
arr_o = np.ones_like(arr)
print(arr_o)

[[1 1 1]
 [1 1 1]]


In [13]:
# np.full_like()
# arr와 동일한 shape의 9로 채워진 배열 생성
arr_f = np.full_like(arr, 9)
print(arr_f)


[[9 9 9]
 [9 9 9]]
