### 1-4. 특정 범위의 값을 가지는 N차원 배열 생성하기

In [1]:
import numpy as np

lst = list(range(0 , 9 , 2))
print(lst)

[0, 2, 4, 6, 8]


In [ ]:
# Using numpy arange() function
arr = np.arange(0 , 9 , 2)
print(arr)
arr = np.arange(3, 12)
print(arr)
arr = np.arange(stop= 9, start= 0 , step= 2) # keyword arguments
print(arr)

[0 2 4 6 8]
[ 3  4  5  6  7  8  9 10 11]
[0 2 4 6 8]


In [ ]:
# Using numpy linspace() function
# np.linspace(start, stop, num=50)
arr = np.linspace(0 , 100 ,120)
print(arr)

[  0.           0.84033613   1.68067227   2.5210084    3.36134454
   4.20168067   5.04201681   5.88235294   6.72268908   7.56302521
   8.40336134   9.24369748  10.08403361  10.92436975  11.76470588
  12.60504202  13.44537815  14.28571429  15.12605042  15.96638655
  16.80672269  17.64705882  18.48739496  19.32773109  20.16806723
  21.00840336  21.8487395   22.68907563  23.52941176  24.3697479
  25.21008403  26.05042017  26.8907563   27.73109244  28.57142857
  29.41176471  30.25210084  31.09243697  31.93277311  32.77310924
  33.61344538  34.45378151  35.29411765  36.13445378  36.97478992
  37.81512605  38.65546218  39.49579832  40.33613445  41.17647059
  42.01680672  42.85714286  43.69747899  44.53781513  45.37815126
  46.21848739  47.05882353  47.89915966  48.7394958   49.57983193
  50.42016807  51.2605042   52.10084034  52.94117647  53.78151261
  54.62184874  55.46218487  56.30252101  57.14285714  57.98319328
  58.82352941  59.66386555  60.50420168  61.34453782  62.18487395
  63.025210

In [14]:
# Using numpy logspace() function
# np.logspace(start, stop, num=50, base=10.0)

arr = np.linspace(1, 10, 10)
print(arr, end = "\n\n")

arr = np.logspace(1, 10, 10, base=2)
print(arr)

arr = np.logspace(0, 5, 6) # default base is 10
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
