### 2-1. 배열의 index 접근하기

In [1]:
import numpy as np

In [ ]:
# 1차원 배열
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

print(arr[3])     # 4번째 요소 출력

[ 1  2  3  4  5  6  7  8  9 10]
4


In [13]:
# 2차원 배열
# ndim은 배열의 차원 수를 반환
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, arr.shape, arr.ndim)
print(arr[1,2])  # 2행 3열 요소 출력
print(arr[:3, 2])  # 모든 행의 3열 요소 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2
6
[3 6 9]
