### 2-3. 배열의 Boolean 인덱싱

In [1]:
import numpy as np

In [9]:
# 1차원 배열
arr = np.array([1, 2, 3, 4, 5])
print(arr[[True, False, True, False, True]]) # Output: [1 3 5]

# 2차원 배열
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(arr_2d[[True, True], True])

[1 3 5]
[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array([[1, 2 , 3, 4],
               [5, 6, 7, 8]])
print(arr[arr > 3])

[4 5 6 7 8]
